name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12  # Match your Python version
        auto-update-conda: true

    - name: Create and activate environment
      run: |
        conda env create --file environment.yml
        conda activate advanced-ai-work

    - name: Install dependencies (if no environment.yml)
      if: !exists('environment.yml')
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
