name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest

      - name: Run black
        run: |
          black --check .

      - name: Run flake8
        run: |
          flake8 .

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Check for tests
        id: check_tests
        run: |
          if [ -d "api/tests" ] && [ "$(ls -A api/tests)" ]; then
            echo "Tests found"
            echo "has_tests=true" >> $GITHUB_ENV
          else
            echo "No tests found, skipping"
            echo "has_tests=false" >> $GITHUB_ENV
          fi

      - name: Run tests
        if: env.has_tests == 'true'
        run: |
          pytest api/tests
