name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install required dependencies
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest==7.4.0 anyio

    # Set PYTHONPATH
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    # Check for tests and execute them if available
    - name: Check for tests
      id: check_tests
      run: |
        if [ -d "api/tests" ] && [ "$(ls -A api/tests)" ]; then
          echo "Tests found"
          echo "has_tests=true" >> $GITHUB_ENV
        else
          echo "No tests found, skipping"
          echo "has_tests=false" >> $GITHUB_ENV
        fi

    - name: Run tests
      if: env.has_tests == 'true'
      run: |
        pytest api/tests

    - name: Skip tests
      if: env.has_tests != 'true'
      run: |
        echo "No tests to run, skipping test stage"
