name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install minimal dependencies
      run: |
        pip install flask pytest==7.4.0

    - name: Check for tests
      id: check_tests
      run: |
        if [ -d "api/tests" ] && [ "$(ls -A api/tests)" ]; then
          echo "Tests found"
          echo "has_tests=true" >> $GITHUB_ENV
        else
          echo "No tests found, skipping"
          echo "has_tests=false" >> $GITHUB_ENV
        fi
        
    - name: Run tests
      if: env.has_tests == 'true'
      run: |
        pytest

        - name: Run tests
        run: |
          if [ -d "api/tests" ] && [ "$(ls -A api/tests)" ]; then
            echo "Tests found, running pytest"
            pytest
          else
            echo "No tests found, skipping"
      